#!/bin/bash
# get CSGO player numbers from gamedig
serverinfo=$(gamedig --type csgo 5.39.85.45:27016)
# jsonquery=$(jq .raw.numplayers)
# playeronline=$($(serverinfo) | $(jsonquery))
# maxplayers=16

echo "$serverinfo/$maxplayers"
# echo $(playeronline)/$(maxplayers)

